# Generated by Django 3.2.10 on 2022-06-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
